<?= $this->build->user->image($row['data']) ?>
<div class="inner">
    <?php if (in_array($row['data']['pm_id'], $this->user->get('unread'))) : ?>
        <label class="label-list">
            <label class="label label-pm"><i class="fas fa-envelope"></i><?= $L_USER_PM_NEW_LABEL ?></label>
        </label>
    <?php endif; ?>
    <a class="fw-700" href="<?= $this->system->url->build('/user/pm/show/' . $row['data']['pm_id'] . '.' . $row['data']['pm_url']) ?>"><?= $row['data']['pm_subject'] ?></a>
    <br>
    <span class="sub-name commas">
        <?php foreach ($row['data']['users'] as $user) : ?>
            <?= $this->build->user->link($user) ?>
        <?php endforeach; ?>
    </span>
</div>