<div class="radio">
    <input type="radio" name="<?= $rowName ?>" id="i<?= $option['data']['icon_id'] ?>" value="<?= $option['data']['icon_id'] ?>" <?php if (isset($option['options']['checked']) and $option['options']['checked'] == true) : ?>checked<?php endif; ?>>
    <label for="i<?= $option['data']['icon_id'] ?>">
        <div></div>
        <span><i class="<?= $option['data']['icon_style'] ?> fa-<?= $option['data']['icon_class_name'] ?>"></i></span>
    </label>
</div>