<?php require $this->template->require('/Blocks/Block/Block'); ?>
<?php require $this->template->require('/Blocks/Field/Field'); ?>
<?php require $this->template->require('/Blocks/Lists/List'); ?>

<?php if (isset($this->data->pagination)) : ?>
    <?php if ($this->data->pagination['enabled'] ?? false === true) : ?>
        <?php require $this->template->require('/Blocks/Pagination'); ?>
    <?php endif; ?>
<?php endif; ?>