<?php require $this->template->require('/Blocks/Block/Block.phtml'); ?>
<?php $cache = array_pop($this->data->list['body']); ?>
<div class="lists">
    <div class="lists-middle"> 
        <?php require $this->template->require('/Blocks/Lists/List.phtml'); ?>
    </div>
</div>
<?php $this->data->list['body'] = ['solved' => $cache]; ?>
<?php require $this->template->require('/Blocks/Lists/List.phtml'); ?>