<?php if (isset($row['options']['template']['big'])) : ?>
    <?php require $row['options']['template']['big']; ?>
<?php else : ?>
    <?php if (isset($row['data']['user_id']) and isset($row['data']['user_name'])) : ?>
        <?= $this->build->user->image($row['data']) ?>
        <div class="inner">
            <span class="list-title"><?= str_starts_with($row['data']['title'], '$') ? substr($row['data']['title'] , 1) : $row['data']['title'] ?></span>
            <br>
            <?= $L_BY ?> <?= $this->build->user->link($row['data'], true) ?><?php if (isset($row['data']['time'])) : ?> <?= $this->build->data->short($row['data']['time']) ?><?php endif; ?>
        </div>
    <?php else : ?>
        <span class="list-title"><?= str_starts_with($row['data']['title'], '$') ? substr($row['data']['title'] , 1) : $row['data']['title'] ?></span>
            <?php if (isset($row['data']['star']) and $row['data']['star'] == 1) : ?>
                <span ajax="title" data-title="<?= ${$row['data']['starTitle']} ?>"><i class="fas fa-star"></i></span>
            <?php endif; ?>
        <?php if (isset($row['data']['desc'])) : ?>
            <br>
            <span><?= str_starts_with($row['data']['desc'], '$') ? substr($row['data']['desc'] , 1) : $row['data']['desc'] ?></span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>