<div class="align wh-full">
    <div class="align wh-full checkbox group--<?= $row['data']['group_class_name'] ?>">
        <input id="gp<?= $row['data']['group_id'] ?>" type="checkbox" name="post_groups[]" value="<?= $row['data']['group_id'] ?>"<?= in_array($row['data']['group_id'], isset($this->data->field['_data']['post']) ? $this->data->field['_data']['post'] : []) ? ' checked' : '' ?>>
        <label for="gp<?= $row['data']['group_id'] ?>">
            <span class="checkbox-icon">
                <i class="fas fa-check"></i>
            </span>
        </label>
    </div>
    <div class="align wh-full checkbox group--<?= $row['data']['group_class_name'] ?>">
        <input id="gt<?= $row['data']['group_id'] ?>" type="checkbox" name="topic_groups[]" value="<?= $row['data']['group_id'] ?>"<?= in_array($row['data']['group_id'], isset($this->data->field['_data']['topic']) ? $this->data->field['_data']['topic'] : []) ? ' checked' : '' ?>>
        <label for="gt<?= $row['data']['group_id'] ?>">
            <span class="checkbox-icon">
                <i class="fas fa-check"></i>
            </span>
        </label>
    </div>
    <div class="align wh-full checkbox group--<?= $row['data']['group_class_name'] ?>">
        <input id="gs<?= $row['data']['group_id'] ?>" type="checkbox" name="see_groups[]" value="<?= $row['data']['group_id'] ?>"<?= in_array($row['data']['group_id'], isset($this->data->field['_data']['see']) ? $this->data->field['_data']['see'] : []) ? ' checked' : '' ?>>
        <label for="gs<?= $row['data']['group_id'] ?>">
            <span class="checkbox-icon">
                <i class="fas fa-check"></i>
            </span>
        </label>
    </div>
</div>