<?php if ($this->data->data['deleted_id']) : ?>
    <div class="page-alert page-alert-type-warning">
        <div class="page-alert-icon">
            <i class="fas fa-trash"></i>
        </div>
        <div class="page-alert-body page-alert-body-flex">
            <div class="page-alert-content">
                <span><?= $L_TOPIC_DELETED ?></span>
            </div>
            <a class="page-alert-button" href="<?= $this->system->url->build('/admin/deleted/show/' . $this->data->data['deleted_id']) ?>"><i class="fas fa-info-circle"></i> <?= $L_DETAILS ?></a>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->data->data['report_id'] and $this->user->perm->has('admin.forum')) : ?>
<div class="page-alert page-alert-type-notification">
        <div class="page-alert-icon">
            <i class="fas fa-exclamation"></i>
        </div>
        <div class="page-alert-body page-alert-body-flex">
            <div class="page-alert-content">
                <span><?= $L_TOPIC_REPORTED ?></span>
            </div>
            <a class="page-alert-button" href="<?= $this->system->url->build('/admin/report/show/' . $this->data->data['report_id']) ?>"><i class="fas fa-info-circle"></i> <?= $L_DETAILS ?></a>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->data->data['is_locked'] == 1) : ?>
    <div class="page-alert page-alert-type-warning">
        <div class="page-alert-icon">
            <i class="fas fa-lock"></i>
        </div>
        <div class="page-alert-body page-alert-body-flex">
            <div class="page-alert-content"><?= $L_TOPIC_LOCKED_ALERT ?></div>
        </div>
    </div>
<?php endif; ?>

<?php require $this->template->require('/Blocks/Panel/Panel'); ?>
<div class="block-list">
    <?php require $this->template->require('/Blocks/Block/Block'); ?>
</div>

<?php require $this->template->require('/Blocks/Pagination'); ?>
