<?= $this->build->user->image($row['data']) ?>
<div class="inner">
    <?php require $this->template->require('/Blocks/Labels'); ?>
    <a class="fw-700" href="<?= $this->build->url->topic($row['data']) ?>"><?= truncate($row['data']['topic_name'], 30) ?></a>
    <br>
    <span class="grey">
        <span class="grey"><?= $L_BY ?> </span>
        <?= $this->build->user->link($row['data']) ?>
        <br>
        <time><?= $this->build->date->long($row['data']['created'], true) ?></time>
    </span>
</div>