<script src="/Assets/jQuery/jQuery.min.js?14"></script>
<script defer src="/Assets/cAjax/cAjax.min.js?22"></script>
<?php if ($this->user->isLogged()) : ?>
    <?php if (isset($this->data->data['editor'])) : ?>
        <script src="/Assets/Trumbowyg/trumbowyg.min.js?<?= $this->system->settings->get('session') ?>"></script>
        <script src="/Assets/Trumbowyg/plugins/emoji/trumbowyg.emoji.min.js?<?= $this->system->settings->get('session') ?>"></script>
        <script src="/Assets/Trumbowyg/plugins/preformatted/trumbowyg.preformatted.min.js"></script>
        <script src="/Assets/Trumbowyg/langs/<?= $this->system->settings->get('site.language_editor') ?>.min.js?<?= $this->system->settings->get('session') ?>"></script>
        <script defer src="/Includes/Template/js/Editor/<?= $this->data->data['editor'] ?>.min.js?13"></script>
    <?php endif; ?>
<?php endif; ?>
<script defer src="/Includes/Template/js/Others.min.js"></script>
<script defer src="/Includes/Template/js/Ajax.min.js?11"></script>
<?php if ($this->system->settings->get('cookie.enabled') == 1) : ?>
    <script src="/Assets/Cookie/Cookie.min.js"></script>
<?php endif; ?>
<?php if (file_exists($path = (ROOT . (defined('ERROR_PAGE') ? TEMPLATE_PATH_DEFAULT : TEMPLATE_PATH) . '/Templates/Blocks/Bottom.phtml'))) : ?>
    <?php require $path ?>
<?php endif; ?>